// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// intLDA
SEXP intLDA(List docs, NumericMatrix alpha, SEXP root, IntegerVector leafmap, int numsamp, int randseed, List init, SEXP qinit_, IntegerVector f_arg);
RcppExport SEXP ITMViz_intLDA(SEXP docsSEXP, SEXP alphaSEXP, SEXP rootSEXP, SEXP leafmapSEXP, SEXP numsampSEXP, SEXP randseedSEXP, SEXP initSEXP, SEXP qinit_SEXP, SEXP f_argSEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< List >::type docs(docsSEXP );
        Rcpp::traits::input_parameter< NumericMatrix >::type alpha(alphaSEXP );
        Rcpp::traits::input_parameter< SEXP >::type root(rootSEXP );
        Rcpp::traits::input_parameter< IntegerVector >::type leafmap(leafmapSEXP );
        Rcpp::traits::input_parameter< int >::type numsamp(numsampSEXP );
        Rcpp::traits::input_parameter< int >::type randseed(randseedSEXP );
        Rcpp::traits::input_parameter< List >::type init(initSEXP );
        Rcpp::traits::input_parameter< SEXP >::type qinit_(qinit_SEXP );
        Rcpp::traits::input_parameter< IntegerVector >::type f_arg(f_argSEXP );
        SEXP __result = intLDA(docs, alpha, root, leafmap, numsamp, randseed, init, qinit_, f_arg);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
