# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

intLDA <- function(docs, alpha, root, leafmap, numsamp, randseed, init, qinit_, f_arg) {
    .Call('ITMViz_intLDA', PACKAGE = 'ITMViz', docs, alpha, root, leafmap, numsamp, randseed, init, qinit_, f_arg)
}

